Repository es-ude/elastic-ai.runtime.enV5, pull requests merged in 2024-08, with the labels that each got.

#246 232 integrate bmi323 library
  .github/workflows/run_checks.yml
  .gitignore
  .idea/vcs.xml
  CMakeLists.txt
  pico_sdk_import.cmake
  picotool/.gitkeep
  src/hal/enV5HwConfiguration/revision01/EnV5HwConfiguration.h
  src/hal/enV5HwConfiguration/revision02/EnV5HwConfiguration.h
  src/hal/sleep/Sleep.c
  src/hal/sleep/include/Sleep.h
  src/network/esp/Esp.c
  src/sensor/CMakeLists.txt
  src/sensor/bmi323/Bmi323.c
  src/sensor/bmi323/CMakeLists.txt
  src/sensor/bmi323/README.adoc
  src/sensor/bmi323/include/Bmi323.h
  src/sensor/sht3x/CMakeLists.txt
  test/hardware/Sensors/CMakeLists.txt
  test/hardware/Sensors/HardwaretestBmi323.c
  test/hardware/Sensors/HardwaretestDualPac193x.c
  test/hardware/Sensors/HardwaretestPac193x.c
  test/hardware/Sensors/HardwaretestPac193xAccumulator.c
  test/hardware/Sensors/HardwaretestPac193xBuffer.c
  test/hardware/Sensors/HardwaretestSht3x.c
  test/hardware/TestConfiguration/HardwaretestConfigureViaHTTP.c
  test/hardware/TestConfiguration/HardwaretestConfigureViaUSB.c
  test/hardware/TestFlash/HardwareTestFlashReadConfiguration.c
  test/hardware/TestFlash/HardwaretestFlash.c
  test/hardware/TestFreeRTOS/HardwaretestFreeRtosQueues.c
  test/hardware/TestFreeRTOS/HardwaretestFreeRtosTask.c
  test/hardware/TestFreeRTOS/HardwaretestSMP.c
  test/hardware/TestMiddleware/HardwaretestMiddleware.c
  test/hardware/TestStub/HardwaretestStub.c
  test/hardware/TestStub/HardwaretestStubWithMonitor.c
  test/unit/dummies/pico/CMakeLists.txt
Labels: enhancement, hardware, sensor

#258 fix(env5-controller): add sleep to fpga on/off
  src/hal/enV5HwController/EnV5HwController.c
Labels: bug

#260 245 implement usb protocol embedded
  .idea/elastic-ai.runtime.enV5.iml
  .idea/vcs.xml
  CMakeLists.txt
  bitfile_scripts/bitfiles/env5_bitfiles/echo_server/env5_top_reconfig_stub_skeleton_v2.bin
  helpers.cmake
  pyproject.toml
  python_utils/__init__.py
  python_utils/usb/README.adoc
  python_utils/usb/__init__.py
  python_utils/usb/communication_base_protocol.py
  python_utils/usb/helper_utils.py
  python_utils/usb/recommended_commands.py
  python_utils/usb/test_communication_base_protocol.py
  python_utils/usb/test_recommended_commands.py
  python_utils/usb/test_user_remote_control.py
  python_utils/usb/user_remote_control.py
  src/fpga/middleware/middleware.c
  src/fpga/stub/include_v2/stub_defs.h
  src/hal/enV5HwConfiguration/revision02/EnV5HwConfiguration.h
  src/hal/enV5HwController/EnV5HwController.c
  src/usb_protocol/CMakeLists.txt
  src/usb_protocol/DefaultCommands.c
  src/usb_protocol/Protocol.c
  src/usb_protocol/Tools.c
  src/usb_protocol/include/UsbProtocolBase.h
  src/usb_protocol/include/UsbProtocolCustomCommands.h
  src/usb_protocol/internal/DefaultCommands.h
  src/usb_protocol/internal/Tools.h
  test/hardware/CMakeLists.txt
  test/hardware/TestUsbProtocol/CMakeLists.txt
  test/hardware/TestUsbProtocol/HardwaretestUsbProtocol.c
Labels: enhancement
