Repository es-ude/elastic-ai.runtime.enV5, pull requests merged in 2024-09, with the labels that each got.

#273 fix(sensor): fix bmi323 library
  src/sensor/bmi323/Bmi323.c
  src/sensor/bmi323/include/Bmi323.h
  test/hardware/Sensors/HardwaretestBmi323.c
Labels: bug

#271 268 usb protocol inference always return the input values instead of output values
  bitfile_scripts/bitfiles/env5_bitfiles/echo_server/env5_top_reconfig_stub_skeleton_v2_add_one.bin
  src/fpga/stub/stub.c
  src/usb_protocol/DefaultCommands.c
Labels: bug

#275 build(cmake): set pico-sdk to specific version
  CMakeLists.txt
Labels: enhancement

#263 Filesystem
  .gitignore
  .idea/cmake.xml
  .idea/codeStyles/Project.xml
  .idea/jsLibraryMappings.xml
  .idea/runConfigurations/all.xml
  .idea/runConfigurations/hardware_test_adxl345b.xml
  .idea/runConfigurations/unit_test_adxl345b.xml
  .idea/vcs.xml
  CMakeLists.txt
  bitfile_scripts/HW-Test_Webserver.py
  helpers.cmake
  src/filesystem/CMakeLists.txt
  src/filesystem/FileSystem.c
  src/filesystem/FileSystemInternal.h
  src/filesystem/include/FileSystem.h
  src/fpga/fpgaConfigurationHandler/FpgaConfigurationHandlerHTTP.c
  src/fpga/fpgaConfigurationHandler/FpgaConfigurationHandlerUSB.c
  src/hal/enV5HwConfiguration/CMakeLists.txt
  src/sensor/sht3x/README.adoc
  test/hardware/CMakeLists.txt
  test/hardware/TestConfiguration/HardwaretestConfigureViaHTTP.c
  test/hardware/TestFlashFileSystem/CMakeLists.txt
  test/hardware/TestFlashFileSystem/DemoFileSystem.c
  test/unit/UnittestFpgaConfigurationHandler.c
Labels: enhancement

#278 233 retrieve pagesectorflash size from cfi
  .idea/vcs.xml
  src/filesystem/FileSystem.c
  src/flash/Flash.c
  src/flash/FlashInternal.h
  src/flash/include/Flash.h
  src/flash/include/FlashTypedefs.h
  src/fpga/fpgaConfigurationHandler/FpgaConfigurationHandlerHTTP.c
  src/fpga/fpgaConfigurationHandler/FpgaConfigurationHandlerInternal.h
  src/fpga/fpgaConfigurationHandler/FpgaConfigurationHandlerUSB.c
  src/hal/enV5HwConfiguration/revision01/EnV5HwConfiguration.h
  src/hal/enV5HwConfiguration/revision02/EnV5HwConfiguration.h
  src/network/esp/CMakeLists.txt
  src/usb_protocol/DefaultCommands.c
  src/usb_protocol/Protocol.c
  src/usb_protocol/Tools.c
  src/usb_protocol/include/UsbProtocolBase.h
  src/usb_protocol/internal/Tools.h
  test/hardware/TestConfiguration/HardwaretestConfigureViaHTTP.c
  test/hardware/TestConfiguration/HardwaretestConfigureViaUSB.c
  test/hardware/TestFlash/HardwareTestFlashReadConfiguration.c
  test/hardware/TestFlash/HardwaretestFlash.c
  test/hardware/TestFlashFileSystem/DemoFileSystem.c
  test/hardware/TestMiddleware/HardwaretestMiddleware.c
  test/hardware/TestStub/HardwaretestStub.c
  test/hardware/TestStub/HardwaretestStubWithMonitor.c
  test/hardware/TestUsbProtocol/HardwaretestUsbProtocol.c
  test/unit/UnittestFpgaConfigurationHandler.c
  test/unit/dummies/flash/Flash.c
Labels: enhancement, hardware

#276 Update commitlint
  .commitlintrc.js
  commitlint.config.js
Labels: documentation, minor priority
