Repository es-ude/elastic-ai.runtime.enV5, pull requests merged in 2024-10, with the labels that each got.

#290 docs(readme): update contribution guidelines
  documentation/CONTRIBUTION.adoc
Labels: documentation

#306 302 bug huntfix reconfiguration
  python_utils/elasticai/runtime/env5/usb/test/test_user_remote_control.py
  python_utils/elasticai/runtime/env5/usb/user_remote_control.py
  run_integration_test.sh
  src/usb_protocol/Tools.c
Labels: bug

#300 Automate dev env setup
  CMakeLists.txt
  helpers.cmake
  requirements.txt
  setup_dev_environment.py
Labels: enhancement

#307 feat(cmake): add custom target functions
  cmake/custom_targets.cmake
Labels: enhancement
